name: Setup toolchain
description: JDK, Clojure CLI, and dependency cache
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: DeLaGuardo/setup-clojure@10.1
      with:
        cli: 1.11.1.1224
    - uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{ hashFiles('deps.edn') }}
