name: tests
run-name: Run test suites
on: pull_request
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Prefetch deps
        shell: bash
        run: |
          clojure -P -M:test:cms
          clojure -P -M:cms:dev:tools

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      # Make /nix/store realization cheap.
      - name: Cache Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-lint-${{ hashFiles('flake.lock', 'flake.nix', '.clj-kondo/**') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-lint-
      - name: Lint with clj-kondo
        run: nix develop .#lint --command bash -c 'clj-kondo --lint src:test:plugins:marx:dev:tools'

  run-unit-and-integration-tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Run unit and integration tests
        run: bin/run-tests cms

  run-e2e-tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Run end-to-end tests
        run: |
          clojure -M:cms:dev:tools -m systems.bread.alpha.dev.main -f dev/main.edn &
          timeout 60 bash -c 'until curl -s -o /dev/null http://localhost:1312/; do sleep 1; done'
          bin/run-tests e2e

  compile-and-test-dev-binary:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      # Install the Nix package manager.
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      # Make /nix/store realization cheap.
      - name: Cache Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-bin-${{ hashFiles('flake.lock', 'flake.nix') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-bin-
          gc-max-store-size-linux: 5G
      - name: Cache Clojure deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
      # Install Nix tooling for building the binary.
      - name: Install the Flake
        run: nix develop .#build --command true
      # Cache source code upstream of the --dev binary.
      - name: Cache dev binary
        id: cache-binary
        uses: actions/cache@v3
        with:
          path: bread.dev
          key: bread-dev-${{ hashFiles('deps.edn', 'flake.lock', 'flake.nix', 'bin/compile', 'src/**', 'cms/**', 'plugins/**', 'resources/**', 'dev/**', 'tools/**') }}
      - name: Compile dev binary
        if: steps.cache-binary.outputs.cache-hit != 'true'
        run: nix develop .#build --command bash -c 'bin/compile --dev'
      - name: Run end-to-end tests against the binary
        run: |
          ./bread.dev -f dev/main.edn &
          timeout 60 bash -c "until curl -s -o /dev/null http://localhost:1312/; do sleep 1; done"
          nix develop .#build --command bin/run-tests e2e
